# Generated by Django 5.0.6 on 2024-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0017_roomtype_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
