# Generated by Django 5.1 on 2024-08-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0018_alter_roomtype_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='CNIC',
        ),
    ]
